Repository jenkinsci/jenkins-infra-test-plugin, pull requests merged in 2022-06, with the labels that each got.

#22 Test https://github.com/jenkins-infra/github-reusable-workflows/pull/3
  .github/workflows/cd.yml
Labels: developer

#23 Tweak docs
  src/main/resources/index.jelly
Labels: documentation

#24 Update baseline to 2.249.x
  pom.xml
Labels: developer

#25 use released version
  .github/workflows/cd.yml
Labels: developer

#26 use test version of incremental maven cd action
  .github/workflows/cd.yml
Labels: developer

#27 use test version of incremental verify ci status action
  .github/workflows/cd.yml
Labels: developer

#28 Add dummy class
  src/main/java/io/jenkins/plugins/jenkinsinfratest/Example.java
Labels: enhancement

#29 Link to Javadoc in core api
  src/main/java/io/jenkins/plugins/jenkinsinfratest/Example.java
Labels: enhancement

#30 Update template
  .github/workflows/cd.yml
Labels: enhancement
